apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: service
spec:
  taints:
    - key: service
      value: "true"
      effect: NoSchedule
  labels:
    nodeType: service-2023
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.large","t3.xlarge"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [ "ap-northeast-2a", "ap-northeast-2c" ]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
  providerRef:
    name: service-lt
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 1209600
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: service-lt
spec:
  subnetSelector:
    karpenter.sh/discovery/fast-cluster: '*'
  securityGroupSelector:
    aws:eks:cluster-name: fast-cluster   # do not change
  tags:
    karpenter.sh/discovery: fast-cluster