version: "3.7"

services:
  fastapi:
    image: order-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload --reload-include templates
    ports:
      - 80:80
    volumes:
      - ./app:/code/app
      - ./templates:/code/templates